name: Deploy example to GitHub Pages

on:
  push:
    branches: ["work"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run tokens:build
      - run: cp examples/index.html dist/index.html
      - run: cp examples/booking-widget.js dist/booking-widget.js
      - run: sed -i 's|./dist/|./|g' dist/index.html
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - id: deployment
        uses: actions/deploy-pages@v4
